// ═══════════════════════════════════════════════════════════════
// Shepherd AI — Curriculum Paths
// 4 paths with modules, passages, and themes
// ═══════════════════════════════════════════════════════════════

export interface CurriculumModule {
  id: string;
  number: number;
  title: string;
  subtitle: string;
  passage: string;
  themes: string[];
  objectives: string[];
  key_questions: string[];
  memory_verse?: string;
  christological_connection: string;
}

export interface CurriculumPath {
  id: string;
  name: string;
  emoji: string;
  subtitle: string;
  description: string;
  weeks: number;
  target_level: number;
  color: string;
  modules: CurriculumModule[];
}

// ═══════════════════════════════════════════════════════════════

export const CURRICULUM: CurriculumPath[] = [
  // ── Seeker's Path (12 weeks) ─────────────────────────────────
  {
    id: "seekers",
    name: "Seeker's Path",
    emoji: "🌱",
    subtitle: "12-Week Foundation",
    description:
      "For new believers and those exploring the Christian faith. Walks through the gospel story from creation to new creation, answering life's biggest questions along the way.",
    weeks: 12,
    target_level: 1,
    color: "#3fb950",
    modules: [
      {
        id: "seek-1", number: 1,
        title: "Who Is God?",
        subtitle: "The Creator and His Character",
        passage: "Genesis 1:1-31",
        themes: ["Creation", "God's Character", "Image of God"],
        objectives: ["Understand that God created everything", "Learn that you are made in God's image", "See God's goodness in creation"],
        key_questions: ["Where did everything come from?", "What is God like?", "Why did God make me?"],
        memory_verse: "Genesis 1:1",
        christological_connection: "Jesus is the Word through whom all things were made (John 1:1-3).",
      },
      {
        id: "seek-2", number: 2,
        title: "What Went Wrong?",
        subtitle: "The Fall and Its Consequences",
        passage: "Genesis 3:1-24",
        themes: ["Sin", "The Fall", "Consequences"],
        objectives: ["Understand why the world is broken", "See how sin separates us from God", "Recognize our need for a Savior"],
        key_questions: ["Why is there suffering?", "What is sin?", "Why do I feel distant from God?"],
        memory_verse: "Romans 3:23",
        christological_connection: "Jesus is the promised seed of the woman who crushes the serpent's head (Genesis 3:15).",
      },
      {
        id: "seek-3", number: 3,
        title: "God's Rescue Plan",
        subtitle: "The Promise of a Savior",
        passage: "Genesis 12:1-9",
        themes: ["Covenant", "Promise", "Faith"],
        objectives: ["See God's plan to bless all nations through Abraham", "Understand what a covenant is", "Learn that salvation is by faith"],
        key_questions: ["How does God fix the brokenness?", "Who are God's chosen people?", "What is a covenant?"],
        memory_verse: "Genesis 12:3",
        christological_connection: "Jesus is the seed of Abraham in whom all nations are blessed (Galatians 3:16).",
      },
      {
        id: "seek-4", number: 4,
        title: "Freedom from Slavery",
        subtitle: "The Exodus and Redemption",
        passage: "Exodus 12:1-14",
        themes: ["Redemption", "Deliverance", "Passover"],
        objectives: ["Understand redemption through the Exodus", "See the Passover lamb as a picture of Jesus", "Learn that God hears the cries of His people"],
        key_questions: ["What does it mean to be redeemed?", "Why did God send the plagues?", "What is the Passover?"],
        memory_verse: "Exodus 6:6",
        christological_connection: "Jesus is our Passover Lamb whose blood covers us (1 Corinthians 5:7).",
      },
      {
        id: "seek-5", number: 5,
        title: "God's Rules for Life",
        subtitle: "The Law and the Heart",
        passage: "Exodus 20:1-17",
        themes: ["Commandments", "Holiness", "Love"],
        objectives: ["Learn the Ten Commandments", "Understand that God's law shows us His character", "See that the law points us to Jesus"],
        key_questions: ["Why did God give rules?", "Can I keep all the commandments?", "What is the greatest commandment?"],
        memory_verse: "Matthew 22:37-38",
        christological_connection: "Jesus fulfilled the law perfectly and summed it up in love (Matthew 5:17, 22:37-40).",
      },
      {
        id: "seek-6", number: 6,
        title: "A King Like No Other",
        subtitle: "David and the Promised Kingdom",
        passage: "2 Samuel 7:1-16",
        themes: ["Kingdom", "Covenant", "Messiah"],
        objectives: ["Learn about God's covenant with David", "Understand the promise of an eternal King", "See David's heart for God"],
        key_questions: ["Why was David called a man after God's heart?", "What is the Davidic covenant?", "Who is the Son of David?"],
        memory_verse: "2 Samuel 7:16",
        christological_connection: "Jesus is the Son of David whose kingdom will never end (Luke 1:32-33).",
      },
      {
        id: "seek-7", number: 7,
        title: "God With Us",
        subtitle: "The Birth of Jesus",
        passage: "Luke 2:1-20",
        themes: ["Incarnation", "Humility", "Joy"],
        objectives: ["Understand the incarnation — God becoming man", "See the humble circumstances of Jesus' birth", "Learn why the angels announced 'good news of great joy'"],
        key_questions: ["Why did God become a man?", "Why was Jesus born in a manger?", "Who were the shepherds?"],
        memory_verse: "John 1:14",
        christological_connection: "Jesus is Immanuel — God with us — fully God and fully man.",
      },
      {
        id: "seek-8", number: 8,
        title: "What Did Jesus Teach?",
        subtitle: "The Sermon on the Mount",
        passage: "Matthew 5:1-16",
        themes: ["Beatitudes", "Kingdom Living", "Salt and Light"],
        objectives: ["Learn the Beatitudes", "Understand what it means to be salt and light", "See Jesus' vision for kingdom living"],
        key_questions: ["What does 'blessed' really mean?", "How should Christians live differently?", "What is the kingdom of heaven?"],
        memory_verse: "Matthew 5:16",
        christological_connection: "Jesus is the teacher who speaks with divine authority, showing us the heart of God.",
      },
      {
        id: "seek-9", number: 9,
        title: "The Greatest Love",
        subtitle: "The Cross of Jesus",
        passage: "John 19:16-30",
        themes: ["Atonement", "Sacrifice", "Love"],
        objectives: ["Understand why Jesus had to die", "See the depth of God's love demonstrated on the cross", "Learn what 'It is finished' means"],
        key_questions: ["Why did Jesus have to die?", "What does the cross accomplish?", "What did Jesus mean by 'It is finished'?"],
        memory_verse: "John 3:16",
        christological_connection: "Jesus is the Lamb of God who takes away the sin of the world (John 1:29).",
      },
      {
        id: "seek-10", number: 10,
        title: "Death Could Not Hold Him",
        subtitle: "The Resurrection",
        passage: "Matthew 28:1-10",
        themes: ["Resurrection", "Victory", "Hope"],
        objectives: ["Understand the historical reality of the resurrection", "See that Jesus conquered death", "Learn why the resurrection changes everything"],
        key_questions: ["Did Jesus really rise from the dead?", "Why is the resurrection so important?", "What does the resurrection mean for me?"],
        memory_verse: "1 Corinthians 15:3-4",
        christological_connection: "Jesus is the firstfruits of the resurrection — because He lives, we will live (1 Corinthians 15:20-22).",
      },
      {
        id: "seek-11", number: 11,
        title: "A New Family",
        subtitle: "The Church Begins",
        passage: "Acts 2:1-47",
        themes: ["Church", "Community", "Holy Spirit"],
        objectives: ["Learn about the birth of the church at Pentecost", "Understand the role of the Holy Spirit", "See what Christian community looks like"],
        key_questions: ["What happened at Pentecost?", "What is the church supposed to be?", "How do I find Christian community?"],
        memory_verse: "Acts 2:42",
        christological_connection: "Jesus is the head of the church, which is His body on earth (Ephesians 1:22-23).",
      },
      {
        id: "seek-12", number: 12,
        title: "Everything Made New",
        subtitle: "The New Creation",
        passage: "Revelation 21:1-7",
        themes: ["New Creation", "Hope", "Eternal Life"],
        objectives: ["See the ultimate hope of the Christian faith", "Understand that God will make all things new", "Learn what eternal life really means"],
        key_questions: ["What will heaven be like?", "What happens when Jesus returns?", "How should I live now in light of eternity?"],
        memory_verse: "Revelation 21:3-4",
        christological_connection: "Jesus is the Alpha and Omega who makes all things new — the story ends with Him.",
      },
    ],
  },

  // ── Disciple's Path (16 weeks) ────────────────────────────────
  {
    id: "disciples",
    name: "Disciple's Path",
    emoji: "🌿",
    subtitle: "16-Week Deep Roots",
    description:
      "For growing believers who want deeper roots in doctrine, character, and practice. Covers the essentials of the Christian life with a Reformed foundation.",
    weeks: 16,
    target_level: 2,
    color: "#d2991d",
    modules: [
      {
        id: "disc-1", number: 1,
        title: "The Word of God",
        subtitle: "Scripture's Authority and Sufficiency",
        passage: "2 Timothy 3:14-17",
        themes: ["Inspiration", "Authority", "Sufficiency"],
        objectives: ["Understand why we trust the Bible", "Learn the doctrine of inspiration", "See that Scripture is sufficient for all of life"],
        key_questions: ["How do we know the Bible is God's Word?", "What does 'inspired' mean?", "Why do we need Scripture?"],
        memory_verse: "2 Timothy 3:16-17",
        christological_connection: "Jesus is the living Word to whom all Scripture points (John 5:39, Luke 24:27).",
      },
      {
        id: "disc-2", number: 2,
        title: "Knowing the Triune God",
        subtitle: "The Doctrine of the Trinity",
        passage: "Matthew 28:18-20",
        themes: ["Trinity", "God's Nature", "Worship"],
        objectives: ["Understand the biblical basis for the Trinity", "Distinguish the persons of the Godhead", "Learn why the Trinity matters for worship and salvation"],
        key_questions: ["How can God be three and one?", "What does each person of the Trinity do?", "Why does the Trinity matter?"],
        memory_verse: "Matthew 28:19",
        christological_connection: "Jesus reveals the Father and sends the Spirit — the Trinity is revealed through Christ.",
      },
      {
        id: "disc-3", number: 3,
        title: "Created and Fallen",
        subtitle: "Human Nature and Sin",
        passage: "Romans 3:9-26",
        themes: ["Anthropology", "Sin", "Total Depravity"],
        objectives: ["Understand what it means to be made in God's image", "Learn the doctrine of total depravity", "See that all have sinned and need grace"],
        key_questions: ["What does the image of God mean after the Fall?", "How sinful am I really?", "Can I do anything good without God?"],
        memory_verse: "Romans 3:23-24",
        christological_connection: "Jesus is the true image of God who restores what Adam lost (Colossians 1:15).",
      },
      {
        id: "disc-4", number: 4,
        title: "Chosen in Christ",
        subtitle: "The Doctrine of Election",
        passage: "Ephesians 1:3-14",
        themes: ["Election", "Predestination", "Assurance"],
        objectives: ["Understand what the Bible teaches about election", "See that election is in Christ and for our comfort", "Address common objections to the doctrine"],
        key_questions: ["Does God choose who is saved?", "What about free will?", "How can I know if I'm elect?"],
        memory_verse: "Ephesians 1:4",
        christological_connection: "Election is always 'in Christ' — He is the Chosen One and we are chosen in union with Him.",
      },
      {
        id: "disc-5", number: 5,
        title: "Saved by Grace Alone",
        subtitle: "Justification by Faith",
        passage: "Romans 5:1-11",
        themes: ["Justification", "Faith", "Grace"],
        objectives: ["Understand the doctrine of justification by faith alone", "Distinguish justification from sanctification", "Learn to rest in Christ's finished work"],
        key_questions: ["How am I made right with God?", "What role do good works play?", "Why is justification by faith alone so important?"],
        memory_verse: "Romans 5:1",
        christological_connection: "Jesus is our righteousness — we are justified by union with Him through faith alone.",
      },
      {
        id: "disc-6", number: 6,
        title: "Growing in Holiness",
        subtitle: "The Doctrine of Sanctification",
        passage: "Romans 6:1-14",
        themes: ["Sanctification", "Holiness", "Mortification"],
        objectives: ["Understand progressive sanctification", "Learn how to put sin to death", "Grasp the role of the Spirit in growth"],
        key_questions: ["How do I become more like Jesus?", "Why do I still struggle with sin?", "What is my role vs. God's role in growth?"],
        memory_verse: "Romans 6:11",
        christological_connection: "We are united to Christ in His death and resurrection — sanctification flows from this union.",
      },
      {
        id: "disc-7", number: 7,
        title: "The Spirit at Work",
        subtitle: "The Person and Work of the Holy Spirit",
        passage: "John 14:15-31",
        themes: ["Holy Spirit", "Indwelling", "Fruit"],
        objectives: ["Understand who the Holy Spirit is", "Learn the Spirit's role in the Christian life", "Recognize the Spirit's work in you"],
        key_questions: ["Is the Holy Spirit a person or a force?", "How does the Spirit help me?", "What are the gifts of the Spirit?"],
        memory_verse: "John 14:26",
        christological_connection: "The Spirit glorifies Christ and makes His presence real to us (John 16:14).",
      },
      {
        id: "disc-8", number: 8,
        title: "The Life of Prayer",
        subtitle: "Communion with God",
        passage: "Matthew 6:5-15",
        themes: ["Prayer", "Communion", "Dependence"],
        objectives: ["Learn to pray as Jesus taught", "Develop a consistent prayer life", "Understand prayer as communion, not just requests"],
        key_questions: ["Why should I pray if God already knows?", "How do I pray when I don't feel like it?", "What does it mean to pray in Jesus' name?"],
        memory_verse: "Matthew 6:9-13",
        christological_connection: "Jesus is our great High Priest who intercedes for us and opens the way to the Father.",
      },
      {
        id: "disc-9", number: 9,
        title: "The Church: Christ's Body",
        subtitle: "Ecclesiology and Community",
        passage: "Ephesians 4:1-16",
        themes: ["Church", "Unity", "Gifts"],
        objectives: ["Understand what the church is and isn't", "Learn the marks of a true church", "Find your role in the body of Christ"],
        key_questions: ["Why do I need the church?", "What makes a church healthy?", "What are spiritual gifts?"],
        memory_verse: "Ephesians 4:4-6",
        christological_connection: "Christ is the head of the church and we are members of His body.",
      },
      {
        id: "disc-10", number: 10,
        title: "The Sacraments",
        subtitle: "Baptism and the Lord's Supper",
        passage: "1 Corinthians 11:23-34",
        themes: ["Baptism", "Lord's Supper", "Covenant"],
        objectives: ["Understand the biblical meaning of baptism", "Learn the significance of the Lord's Supper", "See the sacraments as means of grace"],
        key_questions: ["What does baptism signify?", "Who should be baptized?", "What happens at the Lord's Table?"],
        memory_verse: "1 Corinthians 11:26",
        christological_connection: "The sacraments visibly proclaim Christ's death and resurrection until He returns.",
      },
      {
        id: "disc-11", number: 11,
        title: "Living by Faith",
        subtitle: "Trusting God in Trials",
        passage: "James 1:1-18",
        themes: ["Trials", "Faith", "Perseverance"],
        objectives: ["Learn to count trials as joy", "Understand how testing produces maturity", "Trust God's goodness in suffering"],
        key_questions: ["Why does God allow suffering?", "How do I trust God when life is hard?", "What is the purpose of trials?"],
        memory_verse: "James 1:2-4",
        christological_connection: "Jesus is the suffering servant who sympathizes with our weakness (Hebrews 4:15).",
      },
      {
        id: "disc-12", number: 12,
        title: "The Armor of God",
        subtitle: "Spiritual Warfare",
        passage: "Ephesians 6:10-20",
        themes: ["Spiritual Warfare", "Armor", "Prayer"],
        objectives: ["Understand the reality of spiritual warfare", "Learn to put on the full armor of God", "Stand firm against the schemes of the devil"],
        key_questions: ["Is spiritual warfare real?", "How do I fight spiritual battles?", "What is the armor of God?"],
        memory_verse: "Ephesians 6:11",
        christological_connection: "Each piece of armor corresponds to an attribute of Christ — we put on Christ Himself.",
      },
      {
        id: "disc-13", number: 13,
        title: "Loving Your Neighbor",
        subtitle: "Ethics and the Christian Life",
        passage: "Luke 10:25-37",
        themes: ["Neighbor", "Mercy", "Ethics"],
        objectives: ["Understand what it means to love your neighbor", "Learn to show mercy as Christ showed mercy", "Apply biblical ethics to daily decisions"],
        key_questions: ["Who is my neighbor?", "How do I love difficult people?", "What does Christian love look like in action?"],
        memory_verse: "Luke 10:27",
        christological_connection: "Jesus is the Good Samaritan who rescues us when we are beaten down by sin.",
      },
      {
        id: "disc-14", number: 14,
        title: "Stewarding God's Gifts",
        subtitle: "Time, Talent, and Treasure",
        passage: "Matthew 25:14-30",
        themes: ["Stewardship", "Generosity", "Kingdom"],
        objectives: ["Understand that everything belongs to God", "Learn to steward time, talent, and treasure", "Develop a heart of generosity"],
        key_questions: ["How should I use my money for God's kingdom?", "What am I supposed to do with my talents?", "What does faithful stewardship look like?"],
        memory_verse: "Matthew 25:21",
        christological_connection: "Jesus is the faithful steward who invested His life for us and calls us to do likewise.",
      },
      {
        id: "disc-15", number: 15,
        title: "Making Disciples",
        subtitle: "Evangelism and the Great Commission",
        passage: "Matthew 28:16-20",
        themes: ["Evangelism", "Discipleship", "Mission"],
        objectives: ["Understand the Great Commission", "Learn how to share your faith naturally", "Live with gospel intentionality"],
        key_questions: ["How do I share the gospel without being awkward?", "What is my role in the Great Commission?", "How do I disciple someone?"],
        memory_verse: "Matthew 28:19-20",
        christological_connection: "Jesus commands us to make disciples because He has all authority — we go in His power.",
      },
      {
        id: "disc-16", number: 16,
        title: "Finishing Well",
        subtitle: "Perseverance of the Saints",
        passage: "Romans 8:28-39",
        themes: ["Perseverance", "Assurance", "Glory"],
        objectives: ["Understand the doctrine of perseverance", "Rest in the assurance of salvation", "Fix your eyes on the finish line"],
        key_questions: ["Can I lose my salvation?", "How do I persevere when I feel like giving up?", "What is the golden chain of redemption?"],
        memory_verse: "Romans 8:38-39",
        christological_connection: "Nothing can separate us from the love of God in Christ Jesus — He keeps us to the end.",
      },
    ],
  },

  // ── Teacher's Path (24 weeks) ─────────────────────────────────
  {
    id: "teachers",
    name: "Teacher's Path",
    emoji: "🌳",
    subtitle: "24-Week Teaching Prep",
    description:
      "For those called to teach. Covers hermeneutics, systematic theology, church history, sermon preparation, and group facilitation with a Reformed lens.",
    weeks: 24,
    target_level: 3,
    color: "#58a6ff",
    modules: [
      {
        id: "teach-1", number: 1,
        title: "How to Read the Bible",
        subtitle: "Foundations of Hermeneutics",
        passage: "Nehemiah 8:1-8",
        themes: ["Hermeneutics", "Interpretation", "Clarity"],
        objectives: ["Learn the grammatico-historical method", "Understand genre-sensitive reading", "Practice the analogy of faith principle"],
        key_questions: ["How do I interpret the Bible faithfully?", "What are the rules of hermeneutics?", "How do I avoid reading my ideas into the text?"],
        memory_verse: "2 Timothy 2:15",
        christological_connection: "Christ is the hermeneutical key — all Scripture finds its fulfillment in Him (Luke 24:27).",
      },
      {
        id: "teach-2", number: 2,
        title: "The Story of the Bible",
        subtitle: "Biblical Theology Overview",
        passage: "Luke 24:25-27",
        themes: ["Biblical Theology", "Covenant", "Redemptive History"],
        objectives: ["Trace the Bible's storyline: Creation → Fall → Redemption → New Creation", "Understand the covenant framework", "See Christ in all of Scripture"],
        key_questions: ["What is the main storyline of the Bible?", "How do the covenants relate?", "Why does biblical theology matter?"],
        memory_verse: "Luke 24:27",
        christological_connection: "Every passage finds its place in the Christ-centered storyline of Scripture.",
      },
      {
        id: "teach-3", number: 3,
        title: "The Attributes of God",
        subtitle: "Theology Proper",
        passage: "Isaiah 6:1-7",
        themes: ["Theology Proper", "Holiness", "Sovereignty"],
        objectives: ["Study God's communicable and incommunicable attributes", "Understand divine simplicity and aseity", "Learn to preach God's holiness and love in balance"],
        key_questions: ["What is God like?", "What does it mean that God is holy?", "How do God's attributes relate to each other?"],
        memory_verse: "Isaiah 6:3",
        christological_connection: "Christ is the exact imprint of God's nature — to see Him is to see the Father (Hebrews 1:3).",
      },
      {
        id: "teach-4", number: 4,
        title: "The Person of Christ",
        subtitle: "Christology",
        passage: "Colossians 1:15-23",
        themes: ["Christology", "Incarnation", "Hypostatic Union"],
        objectives: ["Understand the hypostatic union", "Defend the full deity and humanity of Christ", "Trace Christ's three offices: Prophet, Priest, King"],
        key_questions: ["How can Jesus be fully God and fully man?", "Why did the early church fight over Christology?", "What does Christ's exaltation mean?"],
        memory_verse: "Colossians 1:19",
        christological_connection: "In Christ all the fullness of deity dwells bodily — He is the center of all theology.",
      },
      {
        id: "teach-5", number: 5,
        title: "The Work of Christ",
        subtitle: "Atonement Theories",
        passage: "Isaiah 53:1-12",
        themes: ["Atonement", "Substitution", "Propitiation"],
        objectives: ["Understand penal substitutionary atonement", "Survey historical atonement theories", "Preach the cross with theological precision"],
        key_questions: ["What exactly happened on the cross?", "For whom did Christ die?", "How do I explain the atonement to different audiences?"],
        memory_verse: "Isaiah 53:5",
        christological_connection: "Christ bore our sins in His body — the righteous for the unrighteous — to bring us to God (1 Peter 3:18).",
      },
      {
        id: "teach-6", number: 6,
        title: "The Doctrine of Sin",
        subtitle: "Hamartiology",
        passage: "Romans 1:18-32",
        themes: ["Sin", "Total Depravity", "Original Sin"],
        objectives: ["Define sin biblically", "Understand original sin and federal headship", "Distinguish guilt, corruption, and consequences"],
        key_questions: ["What is sin exactly?", "How did Adam's sin affect me?", "Can people do good without God?"],
        memory_verse: "Romans 3:10-12",
        christological_connection: "Christ is the second Adam whose obedience undoes the first Adam's disobedience (Romans 5:18-19).",
      },
      {
        id: "teach-7", number: 7,
        title: "Salvation Applied",
        subtitle: "Ordo Salutis",
        passage: "Romans 8:28-30",
        themes: ["Ordo Salutis", "Effectual Calling", "Glorification"],
        objectives: ["Trace the golden chain of redemption", "Understand each step of salvation's application", "Teach assurance from the order of salvation"],
        key_questions: ["What is the ordo salutis?", "When does regeneration happen?", "How do I know I'm saved?"],
        memory_verse: "Romans 8:30",
        christological_connection: "Every link in the chain of salvation is secured by union with Christ.",
      },
      {
        id: "teach-8", number: 8,
        title: "Covenant Theology",
        subtitle: "Understanding God's Covenants",
        passage: "Hebrews 8:6-13",
        themes: ["Covenant", "Law/Gospel", "Sacraments"],
        objectives: ["Distinguish covenant of works from covenant of grace", "Understand the relationship between the old and new covenants", "Apply covenant theology to preaching"],
        key_questions: ["What is covenant theology?", "How does the old covenant relate to the new?", "Is covenant theology biblical?"],
        memory_verse: "Hebrews 8:10",
        christological_connection: "Christ is the mediator of a better covenant built on better promises (Hebrews 8:6).",
      },
      {
        id: "teach-9", number: 9,
        title: "The Early Church",
        subtitle: "Church History I: Apostolic to Augustine",
        passage: "Acts 2:42-47",
        themes: ["Church History", "Patristics", "Creeds"],
        objectives: ["Trace the church from apostles to Augustine", "Understand the major heresies and councils", "Learn the development of the canon"],
        key_questions: ["How did the early church survive persecution?", "What did the councils decide?", "How did we get the Bible?"],
        memory_verse: "Jude 1:3",
        christological_connection: "The creeds and councils defended the biblical Christ against distortions.",
      },
      {
        id: "teach-10", number: 10,
        title: "The Reformation",
        subtitle: "Church History II: Luther to Westminster",
        passage: "Habakkuk 2:4",
        themes: ["Reformation", "Solas", "Confessions"],
        objectives: ["Understand the five solas of the Reformation", "Trace the Reformation from Luther to Westminster", "Learn the distinctives of Reformed theology"],
        key_questions: ["What caused the Reformation?", "What are the five solas?", "Why do Reformed confessions matter?"],
        memory_verse: "Romans 1:17",
        christological_connection: "The Reformation recovered the biblical gospel: justification by faith alone in Christ alone.",
      },
      {
        id: "teach-11", number: 11,
        title: "Preaching Christ from the Old Testament",
        subtitle: "Christ-Centered Preaching I",
        passage: "Acts 8:26-35",
        themes: ["Typology", "Promise-Fulfillment", "Preaching"],
        objectives: ["Learn to preach Christ from every genre", "Understand legitimate typology vs. allegory", "Practice Christ-centered sermon preparation"],
        key_questions: ["How do I preach Christ from the OT without forcing it?", "What is typology?", "How did the apostles preach the OT?"],
        memory_verse: "Acts 8:35",
        christological_connection: "Beginning with Moses and all the Prophets, Jesus interpreted to them the things concerning Himself.",
      },
      {
        id: "teach-12", number: 12,
        title: "Preaching the Gospels and Epistles",
        subtitle: "Christ-Centered Preaching II",
        passage: "2 Timothy 4:1-5",
        themes: ["Preaching", "Exposition", "Application"],
        objectives: ["Master expository sermon structure", "Learn to move from text to sermon", "Develop Christ-centered application"],
        key_questions: ["How do I structure an expository sermon?", "How do I move from exegesis to application?", "What makes a sermon Christ-centered?"],
        memory_verse: "2 Timothy 4:2",
        christological_connection: "Every sermon must point to Christ who is both the subject and the power of preaching.",
      },
      {
        id: "teach-13", number: 13,
        title: "Leading Small Groups",
        subtitle: "Facilitation and Discipleship",
        passage: "Hebrews 10:24-25",
        themes: ["Small Groups", "Facilitation", "Discipleship"],
        objectives: ["Learn to lead engaging group discussions", "Handle difficult group dynamics", "Create environments for spiritual growth"],
        key_questions: ["How do I facilitate rather than lecture?", "What do I do with the person who dominates?", "How do I foster real community?"],
        memory_verse: "Hebrews 10:24",
        christological_connection: "Jesus modeled small-group discipleship with the Twelve — intimate, intentional, transformative.",
      },
      {
        id: "teach-14", number: 14,
        title: "Counseling from Scripture",
        subtitle: "Biblical Counseling Foundations",
        passage: "Colossians 3:16",
        themes: ["Counseling", "Wisdom", "Sufficiency"],
        objectives: ["Understand biblical (nouthetic) counseling", "Learn to use Scripture in counseling situations", "Know when to refer to professionals"],
        key_questions: ["Is Scripture sufficient for counseling?", "How do I counsel without being preachy?", "What are my limits as a lay counselor?"],
        memory_verse: "Colossians 3:16",
        christological_connection: "Christ is the Wonderful Counselor whose Word and Spirit provide everything for life and godliness.",
      },
      {
        id: "teach-15", number: 15,
        title: "Teaching Children and Youth",
        subtitle: "Age-Appropriate Instruction",
        passage: "Deuteronomy 6:4-9",
        themes: ["Children", "Youth", "Catechesis"],
        objectives: ["Understand developmental stages for teaching", "Learn to use catechisms and storytelling", "Engage youth with honesty and relevance"],
        key_questions: ["How do I teach the Bible to kids?", "What is catechesis?", "How do I keep teenagers engaged?"],
        memory_verse: "Deuteronomy 6:7",
        christological_connection: "Jesus said 'Let the children come to me' — children's ministry is Christ's ministry.",
      },
      {
        id: "teach-16", number: 16,
        title: "The Doctrine of the Church",
        subtitle: "Ecclesiology for Teachers",
        passage: "1 Timothy 3:14-16",
        themes: ["Church", "Polity", "Worship"],
        objectives: ["Understand the marks of a true church", "Learn biblical church government", "Design God-honoring worship"],
        key_questions: ["What makes a church a church?", "How should the church be governed?", "What is the regulative principle?"],
        memory_verse: "1 Timothy 3:15",
        christological_connection: "The church is the household of God, the pillar of truth, built on Christ the cornerstone.",
      },
      {
        id: "teach-17", number: 17,
        title: "Worldviews and Apologetics",
        subtitle: "Defending the Faith",
        passage: "1 Peter 3:13-17",
        themes: ["Apologetics", "Worldview", "Presuppositions"],
        objectives: ["Understand presuppositional apologetics", "Engage competing worldviews critically", "Give a reason for the hope within you"],
        key_questions: ["How do I defend the faith without being argumentative?", "What is presuppositional apologetics?", "How do I engage modern objections?"],
        memory_verse: "1 Peter 3:15",
        christological_connection: "Christ is the truth — all knowledge and wisdom are found in Him (Colossians 2:3).",
      },
      {
        id: "teach-18", number: 18,
        title: "Marriage and Family",
        subtitle: "Biblical Foundations for the Home",
        passage: "Ephesians 5:22-33",
        themes: ["Marriage", "Family", "Gospel"],
        objectives: ["Teach a gospel-centered view of marriage", "Understand roles in the family", "Equip parents for family discipleship"],
        key_questions: ["What does the Bible teach about marriage?", "What are the roles of husband and wife?", "How do I disciple my children?"],
        memory_verse: "Ephesians 5:31-32",
        christological_connection: "Marriage is a profound mystery that points to Christ and the church.",
      },
      {
        id: "teach-19", number: 19,
        title: "Missions and the Nations",
        subtitle: "Global Gospel Proclamation",
        passage: "Revelation 7:9-12",
        themes: ["Missions", "Nations", "Worship"],
        objectives: ["Understand the biblical basis for global missions", "Learn the history of missions movements", "Develop a heart for the unreached"],
        key_questions: ["Why do we need missionaries?", "What is the state of global missions today?", "How can I be involved in missions?"],
        memory_verse: "Revelation 7:9",
        christological_connection: "Christ purchased people from every tribe, tongue, and nation with His blood.",
      },
      {
        id: "teach-20", number: 20,
        title: "Worship That Honors God",
        subtitle: "Theology of Worship",
        passage: "John 4:19-26",
        themes: ["Worship", "Regulative Principle", "Reverence"],
        objectives: ["Understand biblical worship in spirit and truth", "Apply the regulative principle", "Lead worship that exalts Christ"],
        key_questions: ["What is acceptable worship?", "What elements belong in worship?", "How do I lead others in worship?"],
        memory_verse: "John 4:24",
        christological_connection: "Christ is the object and mediator of all true worship — we worship through Him.",
      },
      {
        id: "teach-21", number: 21,
        title: "Handling Controversy",
        subtitle: "Conflict and Peacemaking",
        passage: "Matthew 18:15-20",
        themes: ["Conflict", "Peacemaking", "Church Discipline"],
        objectives: ["Learn biblical conflict resolution", "Understand church discipline redemptively", "Pursue peace without compromising truth"],
        key_questions: ["How do I handle conflict in the church?", "What is church discipline?", "How do I confront in love?"],
        memory_verse: "Matthew 18:15",
        christological_connection: "Christ is our peace who reconciles us to God and to one another (Ephesians 2:14).",
      },
      {
        id: "teach-22", number: 22,
        title: "The Return of Christ",
        subtitle: "Eschatology",
        passage: "1 Thessalonians 4:13-18",
        themes: ["Eschatology", "Second Coming", "Hope"],
        objectives: ["Understand the major millennial views", "Learn what all Christians agree on about the end times", "Live with eternal perspective"],
        key_questions: ["What happens when Jesus returns?", "What are the different end-times views?", "How should eschatology affect how I live?"],
        memory_verse: "1 Thessalonians 4:16-17",
        christological_connection: "Christ will return personally, visibly, and gloriously — our blessed hope.",
      },
      {
        id: "teach-23", number: 23,
        title: "The Pastor's Heart",
        subtitle: "Shepherding God's Flock",
        passage: "1 Peter 5:1-5",
        themes: ["Shepherding", "Leadership", "Humility"],
        objectives: ["Understand the role of an elder/pastor", "Learn to shepherd with humility", "Prepare for pastoral ministry"],
        key_questions: ["What does a pastor do?", "How do I know if I'm called to ministry?", "What are the qualifications for eldership?"],
        memory_verse: "1 Peter 5:2-3",
        christological_connection: "Christ is the Chief Shepherd — undershepherds serve under His authority and by His example.",
      },
      {
        id: "teach-24", number: 24,
        title: "Teaching That Transforms",
        subtitle: "The Goal of All Teaching",
        passage: "Colossians 1:28-29",
        themes: ["Teaching", "Transformation", "Christlikeness"],
        objectives: ["Understand that teaching aims at transformation, not just information", "Present everyone mature in Christ", "Labor with Christ's energy"],
        key_questions: ["What is the goal of all teaching?", "How do I measure teaching success?", "How do I finish my teaching ministry well?"],
        memory_verse: "Colossians 1:28",
        christological_connection: "We proclaim Christ so that we may present everyone mature in Christ — He is the goal.",
      },
    ],
  },

  // ── Scholar's Path (Ongoing) ──────────────────────────────────
  {
    id: "scholars",
    name: "Scholar's Path",
    emoji: "🏛️",
    subtitle: "Ongoing Deep Study",
    description:
      "For advanced students pursuing exegetical depth, theological precision, and original contribution. Self-directed with research modules across biblical studies, systematics, and original languages.",
    weeks: 0, // ongoing
    target_level: 4,
    color: "#a371f7",
    modules: [
      {
        id: "scholar-1", number: 1,
        title: "Biblical Hebrew I",
        subtitle: "Alphabet, Vowels, and Basic Grammar",
        passage: "Genesis 1:1-5",
        themes: ["Hebrew", "Languages", "Exegesis"],
        objectives: ["Learn the Hebrew alphabet and vowel system", "Understand basic noun and verb morphology", "Read Genesis 1:1-5 in Hebrew"],
        key_questions: ["Why study the original languages?", "How does Hebrew grammar affect interpretation?", "What resources are essential for Hebrew study?"],
        christological_connection: "Every Hebrew word ultimately points to the Word made flesh.",
      },
      {
        id: "scholar-2", number: 2,
        title: "Biblical Hebrew II",
        subtitle: "Verbs, Syntax, and Translation",
        passage: "Psalm 23",
        themes: ["Hebrew", "Syntax", "Translation"],
        objectives: ["Master Hebrew verb stems and conjugations", "Analyze Hebrew syntax and clause structure", "Translate Psalm 23 independently"],
        key_questions: ["How does the Hebrew verbal system work?", "What difference does word order make?", "How do I use a Hebrew lexicon?"],
        christological_connection: "The Lord is my Shepherd — Hebrew poetry reveals the depth of our covenant relationship with Christ.",
      },
      {
        id: "scholar-3", number: 3,
        title: "Biblical Greek I",
        subtitle: "Alphabet, Nouns, and Present Tense",
        passage: "John 1:1-5",
        themes: ["Greek", "Languages", "Exegesis"],
        objectives: ["Learn the Greek alphabet and pronunciation", "Understand noun declensions and cases", "Parse present tense verbs"],
        key_questions: ["Why is Greek important for NT study?", "How do cases affect meaning?", "What is the best way to build Greek vocabulary?"],
        christological_connection: "In the beginning was the Logos — Greek philosophy's highest concept becomes flesh in Christ.",
      },
      {
        id: "scholar-4", number: 4,
        title: "Biblical Greek II",
        subtitle: "Participles, Subjunctives, and Exegesis",
        passage: "Romans 8:1-17",
        themes: ["Greek", "Syntax", "Exegesis"],
        objectives: ["Master Greek participles and non-indicative moods", "Diagram Greek sentences for exegesis", "Exegete Romans 8:1-17 from Greek"],
        key_questions: ["How do Greek participles function?", "What do the different moods communicate?", "How do I do Greek word studies responsibly?"],
        christological_connection: "The Spirit Himself bears witness — Greek syntax reveals the intimate work of the Trinity in salvation.",
      },
      {
        id: "scholar-5", number: 5,
        title: "Textual Criticism",
        subtitle: "Reconstructing the Original Text",
        passage: "John 7:53-8:11",
        themes: ["Textual Criticism", "Manuscripts", "Canon"],
        objectives: ["Understand the principles of textual criticism", "Evaluate major textual variants", "Defend the reliability of Scripture"],
        key_questions: ["How do we know we have the original text?", "What are the major textual variants?", "Does textual criticism undermine faith?"],
        christological_connection: "God has preserved His Word so that we may know Christ — textual criticism serves that end.",
      },
      {
        id: "scholar-6", number: 6,
        title: "Septuagint Studies",
        subtitle: "The Greek Old Testament and Its Influence",
        passage: "Deuteronomy 32:43 (LXX vs. MT)",
        themes: ["LXX", "Hellenistic Judaism", "NT Background"],
        objectives: ["Understand the origin and significance of the LXX", "Compare LXX readings with the MT", "Trace LXX influence on NT quotations"],
        key_questions: ["Why is the Septuagint important?", "How did the NT authors use the LXX?", "What are the theological implications of LXX variants?"],
        christological_connection: "The LXX prepared the Greek-speaking world for the gospel — Christ fulfills both Hebrew and Greek Scripture.",
      },
      {
        id: "scholar-7", number: 7,
        title: "Advanced Hermeneutics",
        subtitle: "Philosophical and Theological Foundations",
        passage: "2 Corinthians 3:12-18",
        themes: ["Hermeneutics", "Philosophy", "Tradition"],
        objectives: ["Survey hermeneutical approaches from patristic to postmodern", "Evaluate the new perspective on Paul", "Develop a robust Reformed hermeneutic"],
        key_questions: ["Is there a 'right' way to interpret?", "How does my tradition affect my reading?", "What is theological interpretation of Scripture?"],
        christological_connection: "When one turns to the Lord, the veil is removed — Christ is the hermeneutical key.",
      },
      {
        id: "scholar-8", number: 8,
        title: "Reformed Systematics I",
        subtitle: "Prolegomena through Christology",
        passage: "Romans 11:33-36",
        themes: ["Systematics", "Prolegomena", "Theology Proper"],
        objectives: ["Master prolegomena: Scripture, revelation, theological method", "Defend classical theism", "Articulate Chalcedonian Christology with precision"],
        key_questions: ["What are the sources of theology?", "How do we know God?", "How can Christ be one person with two natures?"],
        christological_connection: "All systematic theology is ultimately Christology — every locus finds its center in Him.",
      },
      {
        id: "scholar-9", number: 9,
        title: "Reformed Systematics II",
        subtitle: "Soteriology through Eschatology",
        passage: "Romans 11:33-36",
        themes: ["Systematics", "Soteriology", "Eschatology"],
        objectives: ["Articulate the ordo salutis with precision", "Defend particular redemption exegetically", "Develop a Reformed eschatology"],
        key_questions: ["For whom did Christ die?", "How does union with Christ ground salvation?", "What must happen before Christ returns?"],
        christological_connection: "From election to glorification, every saving benefit is found in union with Christ.",
      },
      {
        id: "scholar-10", number: 10,
        title: "Pauline Theology",
        subtitle: "Life and Thought of the Apostle",
        passage: "Galatians 2:15-21",
        themes: ["Paul", "Justification", "Union with Christ"],
        objectives: ["Trace Paul's theological development", "Understand the pistis Christou debate", "Articulate Paul's doctrine of union with Christ"],
        key_questions: ["What is the center of Paul's theology?", "Justification or union — which is primary?", "How does Paul read the Old Testament?"],
        christological_connection: "I have been crucified with Christ — Paul's theology is Christology applied to every area of life.",
      },
      {
        id: "scholar-11", number: 11,
        title: "Johannine Literature",
        subtitle: "Gospel, Epistles, and Revelation",
        passage: "John 20:30-31",
        themes: ["John", "Christology", "Eschatology"],
        objectives: ["Understand John's high Christology", "Trace themes of belief, witness, and glory", "Interpret Revelation with a Reformed lens"],
        key_questions: ["How is John's Christology different from the Synoptics?", "What does it mean to 'believe' in John?", "How should we interpret Revelation?"],
        christological_connection: "That you may believe that Jesus is the Christ, the Son of God — John's purpose is Christological.",
      },
      {
        id: "scholar-12", number: 12,
        title: "Original Contribution Project",
        subtitle: "Research, Write, and Contribute",
        passage: "2 Timothy 2:15",
        themes: ["Research", "Writing", "Contribution"],
        objectives: ["Identify a gap in existing scholarship", "Develop a research thesis and methodology", "Produce a publishable paper or resource"],
        key_questions: ["What has no one said yet about this passage?", "How do I make an original contribution?", "Where should I publish or share my work?"],
        christological_connection: "All original contributions serve the church by illuminating Christ more clearly from Scripture.",
      },
    ],
  },
];
